apiVersion: v1
kind: Service
metadata:
  name: springbootapp-service
  namespace: qa
spec:
  selector:
    app: springbootapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
